from flask import Flask, jsonify
from trino.dbapi import connect
from flask_cors import CORS
from trino.auth import BasicAuthentication
import pandas as pd
import urllib3

# Desativa avisos de certificado SSL, se necessário (não recomendado para produção)
urllib3.disable_warnings()

app = Flask(__name__)
CORS(app)

@app.route('/dados', methods=['GET'])
def get_dados():
    conn = connect(
        user="maxwell.silva",
        auth=BasicAuthentication("maxwell.silva", "desktop@230270"),
        http_scheme="https",
        port=443,
        host="k8s-srv01.intradesk",
        catalog="dw_desktop",
        schema="public",
        verify=False,
    )

    cur = conn.cursor()
    
    # Sua consulta SQL
    sql_query = """
SELECT 
  so, 
  data_agendamento, 
  horario, 
  data_abertura_os, 
  data_finalizacao_os, 
  protocolo,
  cidade,
  tecnico, 
  empresa, 
  descricao, 
  status_os, 
  CASE 
    WHEN versao_adm = 1 THEN adm
    WHEN versao_adm = 3 THEN CAST(id_adm AS VARCHAR) 
  END AS pppoe,
  CASE
    WHEN cidade = 'Águas de Santa Bárbara' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Aguas de Santa Barbara' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Agudos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Américo Brasiliense' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Americo Brasiliense' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Am. Brasiliense' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Arandu' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Araraquara' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Arealva' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Areiópolis' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Areiopolis' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Avaré' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Avare' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Bady Bassitt' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Bariri' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Barra Bonita' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Barretos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Bauru' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Bebedouro' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Boa Esperança do Sul' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Boa Esperanca do Sul' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Bocaina' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Borborema' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Borebi' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Botucatu' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Cândido Rodrigues' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Candido Rodrigues' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Cerqueira César' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Cerqueira Cesar' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Colina' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Descalvado' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Dobrada' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Dois Córregos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Dois Corregos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Dourado' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Fernando Prestes' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Gavião Peixoto' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Gaviao Peixoto' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Guaíra' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Guaira' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Guariba' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Guatapará' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Guatapara' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Iacanga' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Iaras' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Ibaté' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Ibate' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Ibitinga' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Igaraçu do Tietê' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Igaracu do Tiete' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Igarapava' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itajobi' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itaí' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itai' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itaju' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itápolis' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itapolis' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itapuí' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itapui' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itatinga' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Itirapina' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Jaborandi' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Jaboticabal' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Jaú' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Jau' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Lençóis Paulista' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Lencois Paulista' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Lins' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Macatuba' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Manduri' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Matão' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Matao' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Mineiros do Tietê' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Mineiros do Tiete' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Monte Alto' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Motuca' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Mirassol' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Nova Europa' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Novo Horizonte' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Óleo' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Oleo' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Olímpia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Olimpia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Paranapanema' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pardinho' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pederneiras' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pindorama' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Piratininga' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pitangueiras' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pradópolis' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pradopolis' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pratânia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pratania' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Ribeirão Bonito' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Ribeirao Bonito' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Rincão' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Rincao' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'São Joaquim da Barra' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Sao Joaquim da Barra' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Santa Adélia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Santa Adelia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Santa Cruz do Rio Pardo' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Santa Ernestina' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Santa Lúcia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Santa Lucia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'São Carlos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Sao Carlos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'São José do Rio Preto' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Sao Jose do Rio Preto' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'S. J. Rio Preto' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'São Manuel' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Sao Manuel' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Tabatinga' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Trabiju' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Araraquara' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Avaré' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Avare' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Barretos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Bauru' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Bebedouro' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Botucatu' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Guaíra' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Guaira' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Ibitinga' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Jaboticabal' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Jaú' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Jau' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Lençois Paulista' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Lencois Paulista' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Lins' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Olímpia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Olimpia' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Pitangueiras' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'São Carlos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Sao Carlos' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'São José do Rio Preto' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Sao Jose do Rio Preto' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Américo Brasiliense' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Americo Brasiliense' THEN 'Regional Centro - Oeste'
	WHEN cidade = 'Bertioga' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Biritiba Mirim' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Caçapava' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Cacapava' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Cubatão' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Cubatao' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Guararema' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Guarujá' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Guaruja' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Guaruja' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Igaratá' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Igarata' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Itanhaém' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Itanhaem' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Jacareí' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Jacarei' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Mogi das Cruzes' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Mongaguá' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Mongagua' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Peruíbe' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Peruibe' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Peruibe' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Praia Grande' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Salesópolis' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Salesopolis' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Santa Branca' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Santos' THEN 'Regional Vale & Sul'
	WHEN cidade = 'São Bernardo do Campo' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Sao Bernardo do Campo' THEN 'Regional Vale & Sul'
	WHEN cidade = 'S. B. do Campo' THEN 'Regional Vale & Sul'
	WHEN cidade = 'São José dos Campos' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Sao Jose dos Campos' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Alumínio' THEN 'Regional Central'
	WHEN cidade = 'Aluminio' THEN 'Regional Central'
	WHEN cidade = 'S. J. Campos' THEN 'Regional Vale & Sul'
	WHEN cidade = 'São Vicente' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Sao Vicente' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Taubaté' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Taubate' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Tremembé' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Tremembe' THEN 'Regional Vale & Sul'
	WHEN cidade = 'São Paulo' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Sao Paulo' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Guararema' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Praia Grande' THEN 'Regional Vale & Sul'
	WHEN cidade = 'São Bernardo do Campo' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Sao Bernardo do Campo' THEN 'Regional Vale & Sul'
	WHEN cidade = 'São José dos Campos' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Sao Jose dos Campos' THEN 'Regional Vale & Sul'
	WHEN cidade = 'São Vicente' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Sao Vicente' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Mogi das Cruzes' THEN 'Regional Vale & Sul'
	WHEN cidade = 'Sumaré' THEN 'Regional Central'
	WHEN cidade = 'Sumare' THEN 'Regional Central'
	WHEN cidade = 'Piracicaba' THEN 'Regional Central'
	WHEN cidade = 'Nova Odessa' THEN 'Regional Central'
	WHEN cidade = 'Santa Barbara do Oeste' THEN 'Regional Central'
	WHEN cidade = 'S. B. Oeste' THEN 'Regional Central'
	WHEN cidade = 'Santa Bárbara d''Oeste' THEN 'Regional Central'
	WHEN cidade = 'Americana' THEN 'Regional Central'
	WHEN cidade = 'Limeira' THEN 'Regional Central'
	WHEN cidade = 'Cordeirópolis' THEN 'Regional Central'
	WHEN cidade = 'Cordeiropolis' THEN 'Regional Central'
	WHEN cidade = 'Capivari' THEN 'Regional Central'
	WHEN cidade = 'Iracemápolis' THEN 'Regional Central'
	WHEN cidade = 'Iracemapolis' THEN 'Regional Central'
	WHEN cidade = 'Araras' THEN 'Regional Central'
	WHEN cidade = 'Santa Gertrudes' THEN 'Regional Central'
	WHEN cidade = 'Conchal' THEN 'Regional Central'
	WHEN cidade = 'Rafard' THEN 'Regional Central'
	WHEN cidade = 'Engenheiro Coelho' THEN 'Regional Central'
	WHEN cidade = 'Eng. Coelho' THEN 'Regional Central'
	WHEN cidade = 'Sorocaba' THEN 'Regional Central'
	WHEN cidade = 'Santa Rita do Passa Quatro' THEN 'Regional Central'
	WHEN cidade = 'S. R. P. Quatro' THEN 'Regional Central'
	WHEN cidade = 'Leme' THEN 'Regional Central'
	WHEN cidade = 'Estiva Gerbi' THEN 'Regional Central'
	WHEN cidade = 'Diadema' THEN 'Regional Central'
	WHEN cidade = 'Guará' THEN 'Regional Central'
	WHEN cidade = 'Guara' THEN 'Regional Central'
	WHEN cidade = 'Itu' THEN 'Regional Central'
	WHEN cidade = 'Aguaí' THEN 'Regional Central'
	WHEN cidade = 'Aguai' THEN 'Regional Central'
	WHEN cidade = 'São Simão' THEN 'Regional Central'
	WHEN cidade = 'Sao Simao' THEN 'Regional Central'
	WHEN cidade = 'Monte Mor' THEN 'Regional Central'
	WHEN cidade = 'São Roque' THEN 'Regional Central'
	WHEN cidade = 'Sao Roque' THEN 'Regional Central'
	WHEN cidade = 'Salto' THEN 'Regional Central'
	WHEN cidade = 'Angatuba' THEN 'Regional Central'
	WHEN cidade = 'Boituva' THEN 'Regional Central'
	WHEN cidade = 'Campina do Monte Alegre' THEN 'Regional Central'
	WHEN cidade = 'Capela do Alto' THEN 'Regional Central'
	WHEN cidade = 'Cerquilho' THEN 'Regional Central'
	WHEN cidade = 'Cesário Lange' THEN 'Regional Central'
	WHEN cidade = 'Cesario Lange' THEN 'Regional Central'
	WHEN cidade = 'Conchas' THEN 'Regional Central'
	WHEN cidade = 'Cristais Paulista' THEN 'Regional Central'
	WHEN cidade = 'Iperó' THEN 'Regional Central'
	WHEN cidade = 'Ipero' THEN 'Regional Central'
	WHEN cidade = 'Itirapuã' THEN 'Regional Central'
	WHEN cidade = 'Itirapua' THEN 'Regional Central'
	WHEN cidade = 'Jumirim' THEN 'Regional Central'
	WHEN cidade = 'Laranjal Paulista' THEN 'Regional Central'
	WHEN cidade = 'Patrocínio Paulista' THEN 'Regional Central'
	WHEN cidade = 'Patrocinio Paulista' THEN 'Regional Central'
	WHEN cidade = 'Pereiras' THEN 'Regional Central'
	WHEN cidade = 'Porangaba' THEN 'Regional Central'
	WHEN cidade = 'Quadra' THEN 'Regional Central'
	WHEN cidade = 'Ribeirão Corrente' THEN 'Regional Central'
	WHEN cidade = 'Ribeirao Corrente' THEN 'Regional Central'
	WHEN cidade = 'Rio das Pedras' THEN 'Regional Central'
	WHEN cidade = 'Saltinho' THEN 'Regional Central'
	WHEN cidade = 'Sarapuí' THEN 'Regional Central'
	WHEN cidade = 'Sarapui' THEN 'Regional Central'
	WHEN cidade = 'Tatuí' THEN 'Regional Central'
	WHEN cidade = 'Tatui' THEN 'Regional Central'
	WHEN cidade = 'Tietê' THEN 'Regional Central'
	WHEN cidade = 'Tiete' THEN 'Regional Central'
	WHEN cidade = 'Franca' THEN 'Regional Central'
	WHEN cidade = 'Casa Branca' THEN 'Regional Central'
	WHEN cidade = 'Mogi Mirim' THEN 'Regional Central'
	WHEN cidade = 'Pirassununga' THEN 'Regional Central'
	WHEN cidade = 'Porto Ferreira' THEN 'Regional Central'
	WHEN cidade = 'Rio Claro' THEN 'Regional Central'
	WHEN cidade = 'Mogi Guaçu' THEN 'Regional Central'
	WHEN cidade = 'Mogi Guacu' THEN 'Regional Central'
	WHEN cidade = 'Votorantim' THEN 'Regional Central'
	WHEN cidade = 'Santa Cruz das Palmeiras' THEN 'Regional Central'
	WHEN cidade = 'S. C. Palmeiras' THEN 'Regional Central'
	WHEN cidade = 'Araras' THEN 'Regional Central'
	WHEN cidade = 'Capivari' THEN 'Regional Central'
	WHEN cidade = 'Limeira' THEN 'Regional Central'
	WHEN cidade = 'Piracicaba' THEN 'Regional Central'
	WHEN cidade = 'Pirassununga' THEN 'Regional Central'
	WHEN cidade = 'Sorocaba' THEN 'Regional Central'
	WHEN cidade = 'Sumaré' THEN 'Regional Central'
	WHEN cidade = 'Sumare' THEN 'Regional Central'
	WHEN cidade = 'Franca' THEN 'Regional Central'
	WHEN cidade = 'Cerquilho' THEN 'Regional Central'
	WHEN cidade = 'Araçoiaba da Serra' THEN 'Regional Central'
	WHEN cidade = 'Aracoiaba da Serra' THEN 'Regional Central'
	WHEN cidade = 'Bofete' THEN 'Regional Central'
	WHEN cidade = 'Cosmópolis' THEN 'Regional Central'
	WHEN cidade = 'Cosmopolis' THEN 'Regional Central'
	WHEN cidade = 'Cosmopolis' THEN 'Regional Central'
	WHEN cidade = 'Cravinhos' THEN 'Regional Central'
	WHEN cidade = 'Paulínia' THEN 'Regional Central'
	WHEN cidade = 'Paulinia' THEN 'Regional Central'
	WHEN cidade = 'Pilar do Sul' THEN 'Regional Central'
	WHEN cidade = 'Ribeirão Preto' THEN 'Regional Central'
	WHEN cidade = 'Ribeirao Preto' THEN 'Regional Central'
	WHEN cidade = 'Campinas' THEN 'Regional Campinas'
	WHEN cidade = 'Jundiaí' THEN 'Regional Campinas'
	WHEN cidade = 'Jundiai' THEN 'Regional Campinas'
	WHEN cidade = 'Caieiras' THEN 'Regional Campinas'
	WHEN cidade = 'Várzea Paulista' THEN 'Regional Campinas'
	WHEN cidade = 'Varzea Paulista' THEN 'Regional Campinas'
	WHEN cidade = 'Franco da Rocha' THEN 'Regional Campinas'
	WHEN cidade = 'Indaiatuba' THEN 'Regional Campinas'
	WHEN cidade = 'Campo Limpo Paulista' THEN 'Regional Campinas'
	WHEN cidade = 'Campo Limpo Pt.' THEN 'Regional Campinas'
	WHEN cidade = 'Valinhos' THEN 'Regional Campinas'
	WHEN cidade = 'Vinhedo' THEN 'Regional Campinas'
	WHEN cidade = 'Itupeva' THEN 'Regional Campinas'
	WHEN cidade = 'Cabreúva' THEN 'Regional Campinas'
	WHEN cidade = 'Cabreuva' THEN 'Regional Campinas'
	WHEN cidade = 'Louveira' THEN 'Regional Campinas'
	WHEN cidade = 'Araçariguama' THEN 'Regional Campinas'
	WHEN cidade = 'Aracariguama' THEN 'Regional Campinas'
	WHEN cidade = 'Francisco Morato' THEN 'Regional Campinas'
	WHEN cidade = 'Francis. Morato' THEN 'Regional Campinas'
	WHEN cidade = 'Hortolândia' THEN 'Regional Campinas'
	WHEN cidade = 'Hortolandia' THEN 'Regional Campinas'
	WHEN cidade = 'Jaguariúna' THEN 'Regional Campinas'
	WHEN cidade = 'Jaguariuna' THEN 'Regional Campinas'
	WHEN cidade = 'Santo Antônio de Posse' THEN 'Regional Campinas'
	WHEN cidade = 'Santo Antonio de Posse' THEN 'Regional Campinas'
	WHEN cidade = 'St. Ant. Posse' THEN 'Regional Campinas'
	WHEN cidade = 'Holambra' THEN 'Regional Campinas'
	WHEN cidade = 'Pedreira' THEN 'Regional Campinas'
	WHEN cidade = 'Caieiras' THEN 'Regional Campinas'
	WHEN cidade = 'Sumare' THEN 'Regional Central'
	WHEN cidade = 'Mairipora' THEN 'Regional Campinas'
	WHEN cidade = 'Campinas' THEN 'Regional Campinas'
	WHEN cidade = 'Jaguariúna' THEN 'Regional Campinas'
	WHEN cidade = 'Jaguariuna' THEN 'Regional Campinas'
	WHEN cidade = 'Jundiaí' THEN 'Regional Campinas'
	WHEN cidade = 'Jundiai' THEN 'Regional Campinas'
	WHEN cidade = 'Amparo' THEN 'Regional Campinas'
	WHEN cidade = 'Atibaia' THEN 'Regional Campinas'
	WHEN cidade = 'Bom Jesus dos Perdões' THEN 'Regional Campinas'
	WHEN cidade = 'Bom Jesus dos Perdoes' THEN 'Regional Campinas'
	WHEN cidade = 'Bom Jesus dos P' THEN 'Regional Campinas'
	WHEN cidade = 'Bragança Paulista' THEN 'Regional Campinas'
	WHEN cidade = 'Braganca Paulista' THEN 'Regional Campinas'
	WHEN cidade = 'Itatiba' THEN 'Regional Campinas'
	WHEN cidade = 'Jarinu' THEN 'Regional Campinas'
	WHEN cidade = 'Lindóia' THEN 'Regional Campinas'
	WHEN cidade = 'Lindoia' THEN 'Regional Campinas'
	WHEN cidade = 'Mairiporã' THEN 'Regional Campinas'
	WHEN cidade = 'Mairipora' THEN 'Regional Campinas'
	WHEN cidade = 'Monte Alegre do Sul' THEN 'Regional Campinas'
	WHEN cidade = 'Nazaré Paulista' THEN 'Regional Campinas'
	WHEN cidade = 'Nazare Paulista' THEN 'Regional Campinas'
	WHEN cidade = 'Piracaia' THEN 'Regional Campinas'
	WHEN cidade = 'Serra Negra' THEN 'Regional Campinas'
END AS Regional,
CASE
    WHEN descricao  = 'Manutenção / Suporte' THEN 'Reparo'
    END AS Status
FROM dw_desktop.public.vi_ordem_servico
WHERE CAST(data_agendamento AS DATE) = CURRENT_DATE
"""

    cur.execute(sql_query)

    # Recupere os resultados em um DataFrame
    df = pd.DataFrame(cur.fetchall(), columns=[desc[0] for desc in cur.description])

    
    colunas_data_hora = ['data_agendamento', 'horario', 'data_abertura_os', 'data_finalizacao_os']
    for coluna in colunas_data_hora:
        df[coluna] = df[coluna].astype('str').replace('NaT', '')
    
    # Converta o DataFrame para um dicionário em formato JSON
    data_json = df.to_dict(orient='records')
    
    # Fecha a conexão e retorna os dados
    return jsonify(data_json)

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5000, debug=True)
